# Generated by Django 5.1.3 on 2024-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(choices=[('BRI', [('name', 'Brisbane Broncos'), ('color', '#7A003C')]), ('CBR', [('name', 'Canberra Raiders'), ('color', '#64A300')]), ('CAN', [('name', 'Canterbury Bulldogs'), ('color', '#00338D')]), ('CRO', [('name', 'Cronulla-Sutherland Sharks'), ('color', '#0096D6')]), ('DOL', [('name', 'Redcliffe Dolphins'), ('color', '#E30613')]), ('GLD', [('name', 'Gold Coast Titans'), ('color', '#005F9E')]), ('MAN', [('name', 'Manly-Warringah Sea Eagles'), ('color', '#6C003F')]), ('MEL', [('name', 'Melbourne Storm'), ('color', '#432276')]), ('NEW', [('name', 'Newcastle Knights'), ('color', '#00338D')]), ('NQL', [('name', 'North Queensland Cowboys'), ('color', '#041E42')]), ('NZW', [('name', 'New Zealand Warriors'), ('color', '#000000')]), ('PAR', [('name', 'Parramatta Eels'), ('color', '#FFD700')]), ('PEN', [('name', 'Penrith Panthers'), ('color', '#231F20')]), ('SOU', [('name', 'South Sydney Rabbitohs'), ('color', '#006C2C')]), ('STI', [('name', 'St George Illawarra Dragons'), ('color', '#D50032')]), ('SYD', [('name', 'Sydney Roosters'), ('color', '#001E62')]), ('WST', [('name', 'West Tigers'), ('color', '#FF6600')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(choices=[('BRI', [('name', 'Brisbane Broncos'), ('color', '#7A003C')]), ('CBR', [('name', 'Canberra Raiders'), ('color', '#64A300')]), ('CAN', [('name', 'Canterbury Bulldogs'), ('color', '#00338D')]), ('CRO', [('name', 'Cronulla-Sutherland Sharks'), ('color', '#0096D6')]), ('DOL', [('name', 'Redcliffe Dolphins'), ('color', '#E30613')]), ('GLD', [('name', 'Gold Coast Titans'), ('color', '#005F9E')]), ('MAN', [('name', 'Manly-Warringah Sea Eagles'), ('color', '#6C003F')]), ('MEL', [('name', 'Melbourne Storm'), ('color', '#432276')]), ('NEW', [('name', 'Newcastle Knights'), ('color', '#00338D')]), ('NQL', [('name', 'North Queensland Cowboys'), ('color', '#041E42')]), ('NZW', [('name', 'New Zealand Warriors'), ('color', '#000000')]), ('PAR', [('name', 'Parramatta Eels'), ('color', '#FFD700')]), ('PEN', [('name', 'Penrith Panthers'), ('color', '#231F20')]), ('SOU', [('name', 'South Sydney Rabbitohs'), ('color', '#006C2C')]), ('STI', [('name', 'St George Illawarra Dragons'), ('color', '#D50032')]), ('SYD', [('name', 'Sydney Roosters'), ('color', '#001E62')]), ('WST', [('name', 'West Tigers'), ('color', '#FF6600')])], max_length=100),
        ),
    ]
