# Generated by Django 5.1.3 on 2024-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_away_score_alter_match_away_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(choices=[('BRI', 'Brisbane Broncos'), ('CBR', 'Canberra Raiders'), ('CAN', 'Canterbury Bulldogs'), ('CRO', 'Cronulla-Sutherland Sharks'), ('DOL', 'Redcliffe Dolphins'), ('GLD', 'Gold Coast Titans'), ('MAN', 'Manly-Warringah Sea Eagles'), ('MEL', 'Melbourne Storm'), ('NEW', 'Newcastle Knights'), ('NQL', 'North Queensland Cowboys'), ('NZW', 'New Zealand Warriors'), ('PAR', 'Parramatta Eels'), ('PEN', 'Penrith Panthers'), ('SOU', 'South Sydney Rabbitohs'), ('STI', 'St George Illawarra Dragons'), ('SYD', 'Sydney Roosters'), ('WST', 'West Tigers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(choices=[('BRI', 'Brisbane Broncos'), ('CBR', 'Canberra Raiders'), ('CAN', 'Canterbury Bulldogs'), ('CRO', 'Cronulla-Sutherland Sharks'), ('DOL', 'Redcliffe Dolphins'), ('GLD', 'Gold Coast Titans'), ('MAN', 'Manly-Warringah Sea Eagles'), ('MEL', 'Melbourne Storm'), ('NEW', 'Newcastle Knights'), ('NQL', 'North Queensland Cowboys'), ('NZW', 'New Zealand Warriors'), ('PAR', 'Parramatta Eels'), ('PEN', 'Penrith Panthers'), ('SOU', 'South Sydney Rabbitohs'), ('STI', 'St George Illawarra Dragons'), ('SYD', 'Sydney Roosters'), ('WST', 'West Tigers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_location',
            field=models.CharField(choices=[('BRI', 'Suncorp Stadium'), ('CBR', 'GIO Stadium'), ('CAN', 'Accor Stadium'), ('CAN SND', 'Belmore Sports Ground'), ('CRO', 'PointsBet Stadium'), ('DOL', 'Dolphin Stadium'), ('DOL SND', 'Dolphin Stadium'), ('DOL THD', 'Sunshine Coast Stadium'), ('GLD', 'Cbus Super Stadium'), ('MAN', '4 Pines Park'), ('MEL', 'AAMI Park'), ('NEW', 'McDonald Jones Stadium'), ('NZW', 'Go Media Stadium'), ('NQL', 'Queensland Country Bank Stadium'), ('PAR', 'CommBank Stadium'), ('PEN', 'Commbank Stadium'), ('SOU', 'Accor Stadium'), ('STI', 'Netstrata Jubilee Stadium'), ('STI SND', 'WIN Stadium'), ('SYD', 'Allianz Stadium'), ('WST', 'Leichhardt Oval'), ('WST SND', 'Campbelltown Sports Stadium')], max_length=100),
        ),
    ]
