# Generated by Django 5.1.3 on 2024-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_away_team_alter_match_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Full Time', 'Full Time'), ('Half Time', 'Half Time'), ('Extra Time', 'Extra Time'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled'), ('Abandoned', 'Abandoned')], default='Scheduled', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(choices=[('BRI', 'Brisbane Broncos'), ('CBR', 'Canberra Raiders'), ('CAN', 'Canterbury Bulldogs'), ('CRO', 'Cronulla-Sutherland Sharks'), ('DOL', 'Redcliffe Dolphins'), ('GLD', 'Gold Coast Titans'), ('MAN', 'Manly-Warringah Sea Eagles'), ('MEL', 'Melbourne Storm'), ('NEW', 'Newcastle Knights'), ('NQL', 'North Queensland Cowboys'), ('NZW', 'New Zealand Warriors'), ('PAR', 'Parramatta Eels'), ('PEN', 'Penrith Panthers'), ('SOU', 'South Sydney Rabbitohs'), ('STI', 'St George Illawarra Dragons'), ('SYD', 'Sydney Roosters'), ('WST', 'Wests Tigers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='draw_odds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(choices=[('BRI', 'Brisbane Broncos'), ('CBR', 'Canberra Raiders'), ('CAN', 'Canterbury Bulldogs'), ('CRO', 'Cronulla-Sutherland Sharks'), ('DOL', 'Redcliffe Dolphins'), ('GLD', 'Gold Coast Titans'), ('MAN', 'Manly-Warringah Sea Eagles'), ('MEL', 'Melbourne Storm'), ('NEW', 'Newcastle Knights'), ('NQL', 'North Queensland Cowboys'), ('NZW', 'New Zealand Warriors'), ('PAR', 'Parramatta Eels'), ('PEN', 'Penrith Panthers'), ('SOU', 'South Sydney Rabbitohs'), ('STI', 'St George Illawarra Dragons'), ('SYD', 'Sydney Roosters'), ('WST', 'Wests Tigers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_location',
            field=models.CharField(choices=[('BRI', 'Suncorp Stadium'), ('CBR', 'GIO Stadium'), ('CAN', 'Accor Stadium'), ('CAN SND', 'Belmore Sports Ground'), ('CRO', 'PointsBet Stadium'), ('DOL', 'Dolphin Stadium'), ('DOL SND', 'Sunshine Coast Stadium'), ('DOL TER', 'Suncorp Stadium'), ('GLD', 'Cbus Super Stadium'), ('MAN', '4 Pines Park'), ('MEL', 'AAMI Park'), ('NEW', 'McDonald Jones Stadium'), ('NZW', 'Go Media Stadium'), ('NQL', 'Queensland Country Bank Stadium'), ('PAR', 'CommBank Stadium'), ('PEN', 'Commbank Stadium'), ('SOU', 'Accor Stadium'), ('STI', 'Netstrata Jubilee Stadium'), ('STI SND', 'WIN Stadium'), ('SYD', 'Allianz Stadium'), ('WST', 'Leichhardt Oval'), ('WST SND', 'Campbelltown Sports Stadium')], max_length=100),
        ),
    ]
