# Generated by Django 5.1.3 on 2024-11-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('matches', '0004_match_status_alter_match_away_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_odds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('draw_odds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('away_odds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_choice', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away'), ('draw', 'Draw')], max_length=100, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
            options={
                'verbose_name': 'User Bet',
                'verbose_name_plural': 'User Bets',
                'db_table': 'user_bets',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
