# Generated by Django 5.1.3 on 2024-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_userbet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
