# Generated by Django 5.1.3 on 2024-12-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_userbet_id_alter_userbet_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbet',
            unique_together=set(),
        ),
    ]
